from __future__ import annotations

from typing import Any, Dict

try:
    from ._diffusers_repo_runtime import media_publish_node
    from ._model_workflow_common import BASE_PARAMS_SCHEMA
except Exception:
    from _diffusers_repo_runtime import media_publish_node
    from _model_workflow_common import BASE_PARAMS_SCHEMA


NAME = "models.diffusers_repo_media_encode"
PERMISSIONS = ["models.diffusers_repo_media_encode", "models.*"]


def run(ctx: Dict[str, Any], params: Dict[str, Any]) -> Dict[str, Any]:
    return media_publish_node(ctx or {}, params or {})


TOOL_SPEC = {
    "id": NAME,
    "category": "models",
    "label": "Models: Diffusers Repo Media Publish",
    "description": "Publish the MP4 generated by a repo-based diffusers pipeline as the workflow file result.",
    "permissions": PERMISSIONS,
    "params_schema": BASE_PARAMS_SCHEMA,
}

