from __future__ import annotations

DEFAULT_SETTINGS = {
    "workflow_exchange_enabled": True,
    "workflow_exchange_mode": "hybrid",
    "workflow_exchange_public_publish_enabled": True,
    "workflow_exchange_private_publish_enabled": True,
    "workflow_exchange_public_bundle_mode": "spec_only",
    "workflow_exchange_private_bundle_mode": "spec_only",
    "workflow_exchange_private_allow_trusted_code": True,
    "workflow_exchange_allow_custom_code_public": False,
    "workflow_exchange_allow_custom_code_private": True,
    "workflow_exchange_public_min_safety_score": 0.95,
    "workflow_exchange_public_min_quality_score": 0.70,
    "workflow_exchange_private_min_quality_score": 0.60,
    "workflow_exchange_auto_install_private_curated": False,
    "workflow_exchange_auto_update_private_curated": True,
    "workflow_exchange_auto_install_public": False,
    "workflow_exchange_auto_update_public": False,
    "workflow_exchange_private_federation_id": "",
    "workflow_exchange_allowed_federation_keys": [],
    "workflow_exchange_allowed_mirrors": [],
    "workflow_exchange_public_relays": ["https://account.gotchat.ai/api"],
    "workflow_exchange_private_relays": ["http://host.docker.internal:5001"],
    "workflow_exchange_public_timeout_s": 12,
    "workflow_exchange_public_scheduled_sync_enabled": False,
    "workflow_exchange_public_sync_min_interval_s": 300,
    "workflow_exchange_private_sync_min_interval_s": 60,
    "workflow_exchange_private_scheduled_sync_enabled": False,
    "workflow_exchange_sanitize_public_profile": "public_strict",
    "workflow_exchange_sanitize_private_profile": "private_org",
    "workflow_exchange_placeholder_style": "typed",
    "workflow_exchange_publish_top_k": 10,
    "workflow_exchange_exclude_share_skills": [],
    "workflow_exchange_exclude_share_skill_categories": ["custom_code"],
    "workflow_exchange_exclude_share_tags": [],
    "workflow_exchange_exclude_share_titles": [],
    "workflow_exchange_exclude_share_title_regex": [],
    "workflow_exchange_exclude_update_skills": [],
    "workflow_exchange_exclude_update_skill_categories": [],
    "workflow_exchange_exclude_update_tags": [],
    "workflow_exchange_exclude_update_titles": [],
    "workflow_exchange_exclude_update_title_regex": [],
    "workflow_exchange_exclude_install_publishers": [],
    "workflow_exchange_exclude_install_federations": [],
    "workflow_exchange_public_strip_code_on_import": True,
    "workflow_exchange_public_block_if_code_present": False,
    "workflow_exchange_private_require_signature_for_code": True,
}


SETTINGS_SCHEMA = [
    {
        "key": "workflow_exchange_enabled",
        "label": "Enable Workflow Exchange",
        "type": "bool",
        "default": DEFAULT_SETTINGS["workflow_exchange_enabled"],
        "help": "Enable workflow exchange features for publishing, importing, and installing shared workflows.",
    },
    {
        "key": "workflow_exchange_mode",
        "label": "Workflow Exchange Mode",
        "type": "select",
        "default": DEFAULT_SETTINGS["workflow_exchange_mode"],
        "options": ["off", "private", "public", "hybrid"],
        "help": "Choose whether workflow exchange is disabled, private-only, public-only, or hybrid.",
    },
    {
        "key": "workflow_exchange_public_bundle_mode",
        "label": "Public Bundle Mode",
        "type": "select",
        "default": DEFAULT_SETTINGS["workflow_exchange_public_bundle_mode"],
        "options": ["spec_only"],
        "help": "Public sharing defaults to spec-only bundles so custom code is not distributed.",
    },
    {
        "key": "workflow_exchange_private_bundle_mode",
        "label": "Private Bundle Mode",
        "type": "select",
        "default": DEFAULT_SETTINGS["workflow_exchange_private_bundle_mode"],
        "options": ["spec_only", "trusted_code"],
        "help": "Private sharing can remain spec-only or optionally include signed trusted code.",
    },
    {
        "key": "workflow_exchange_public_publish_enabled",
        "label": "Enable Public Publish",
        "type": "bool",
        "default": DEFAULT_SETTINGS["workflow_exchange_public_publish_enabled"],
        "help": "Allow publishing sanitized public exchange bundles.",
    },
    {
        "key": "workflow_exchange_private_publish_enabled",
        "label": "Enable Private Publish",
        "type": "bool",
        "default": DEFAULT_SETTINGS["workflow_exchange_private_publish_enabled"],
        "help": "Allow publishing private or org exchange bundles.",
    },
    {
        "key": "workflow_exchange_public_relays",
        "label": "Public Relay URLs",
        "type": "list",
        "default": DEFAULT_SETTINGS["workflow_exchange_public_relays"],
        "help": "Relay base URLs used for public anonymous distribution and discovery.",
    },
    {
        "key": "workflow_exchange_private_relays",
        "label": "Private Relay URLs",
        "type": "list",
        "default": DEFAULT_SETTINGS["workflow_exchange_private_relays"],
        "help": "User-owned local or private relay base URLs used for private mirror push and pull.",
    },
    {
        "key": "workflow_exchange_private_federation_id",
        "label": "Private Federation Id",
        "type": "string",
        "default": DEFAULT_SETTINGS["workflow_exchange_private_federation_id"],
        "help": "Federation identifier used for private or org exchange grouping.",
    },
    {
        "key": "workflow_exchange_allowed_federation_keys",
        "label": "Allowed Federation Keys",
        "type": "list",
        "default": DEFAULT_SETTINGS["workflow_exchange_allowed_federation_keys"],
        "help": "Trusted signing keys that private bundles may use for custom code.",
    },
    {
        "key": "workflow_exchange_allowed_mirrors",
        "label": "Allowed Mirrors",
        "type": "list",
        "default": DEFAULT_SETTINGS["workflow_exchange_allowed_mirrors"],
        "help": "Optional mirror allowlist for private or org exchange sync.",
    },
    {
        "key": "workflow_exchange_public_scheduled_sync_enabled",
        "label": "Enable Public Scheduled Sync",
        "type": "bool",
        "default": DEFAULT_SETTINGS["workflow_exchange_public_scheduled_sync_enabled"],
        "help": "Allow low-frequency scheduled public sync. Disable to keep public sync manual-only.",
    },
    {
        "key": "workflow_exchange_public_sync_min_interval_s",
        "label": "Public Sync Min Interval (Seconds)",
        "type": "number",
        "default": DEFAULT_SETTINGS["workflow_exchange_public_sync_min_interval_s"],
        "help": "Recommended low-frequency public sync floor for relay-assisted anonymous updates.",
    },
    {
        "key": "workflow_exchange_private_sync_min_interval_s",
        "label": "Private Sync Min Interval (Seconds)",
        "type": "number",
        "default": DEFAULT_SETTINGS["workflow_exchange_private_sync_min_interval_s"],
        "help": "Minimum interval between private/org sync passes when scheduled or automated sync is enabled.",
    },
    {
        "key": "workflow_exchange_private_scheduled_sync_enabled",
        "label": "Enable Private Scheduled Sync",
        "type": "bool",
        "default": DEFAULT_SETTINGS["workflow_exchange_private_scheduled_sync_enabled"],
        "help": "Private/org mode may opt into scheduled sync. Public mode should remain manual or low-frequency.",
    },
    {
        "key": "workflow_exchange_public_timeout_s",
        "label": "Public Relay Timeout (Seconds)",
        "type": "number",
        "default": DEFAULT_SETTINGS["workflow_exchange_public_timeout_s"],
        "help": "Timeout used for public relay pull and push requests.",
    },
    {
        "key": "workflow_exchange_public_min_safety_score",
        "label": "Public Minimum Safety Score",
        "type": "number",
        "default": DEFAULT_SETTINGS["workflow_exchange_public_min_safety_score"],
        "help": "Public publish threshold for sanitized safety score.",
    },
    {
        "key": "workflow_exchange_public_min_quality_score",
        "label": "Public Minimum Quality Score",
        "type": "number",
        "default": DEFAULT_SETTINGS["workflow_exchange_public_min_quality_score"],
        "help": "Public publish threshold for workflow quality score.",
    },
    {
        "key": "workflow_exchange_private_min_quality_score",
        "label": "Private Minimum Quality Score",
        "type": "number",
        "default": DEFAULT_SETTINGS["workflow_exchange_private_min_quality_score"],
        "help": "Private or org quality floor for review and install decisions.",
    },
    {
        "key": "workflow_exchange_public_strip_code_on_import",
        "label": "Strip Code On Public Import",
        "type": "bool",
        "default": DEFAULT_SETTINGS["workflow_exchange_public_strip_code_on_import"],
        "help": "Strip trusted code from imported public bundles before local registration.",
    },
    {
        "key": "workflow_exchange_public_block_if_code_present",
        "label": "Block Public Import If Code Present",
        "type": "bool",
        "default": DEFAULT_SETTINGS["workflow_exchange_public_block_if_code_present"],
        "help": "Block public imports entirely when executable custom code is present.",
    },
    {
        "key": "workflow_exchange_private_require_signature_for_code",
        "label": "Require Signature For Private Code",
        "type": "bool",
        "default": DEFAULT_SETTINGS["workflow_exchange_private_require_signature_for_code"],
        "help": "Require trusted signature verification before private custom code is accepted.",
    },
    {
        "key": "workflow_exchange_private_allow_trusted_code",
        "label": "Allow Trusted Private Code",
        "type": "bool",
        "default": DEFAULT_SETTINGS["workflow_exchange_private_allow_trusted_code"],
        "help": "Permit trusted private bundles to include signed custom skills.",
    },
    {
        "key": "workflow_exchange_auto_install_private_curated",
        "label": "Auto Install Private Curated",
        "type": "bool",
        "default": DEFAULT_SETTINGS["workflow_exchange_auto_install_private_curated"],
        "help": "Automatically install trusted curated private workflows when policy allows.",
    },
    {
        "key": "workflow_exchange_auto_update_private_curated",
        "label": "Auto Update Private Curated",
        "type": "bool",
        "default": DEFAULT_SETTINGS["workflow_exchange_auto_update_private_curated"],
        "help": "Automatically update trusted curated private workflows when policy allows.",
    },
    {
        "key": "workflow_exchange_auto_install_public",
        "label": "Auto Install Public",
        "type": "bool",
        "default": DEFAULT_SETTINGS["workflow_exchange_auto_install_public"],
        "help": "Automatically install public bundles that pass safety and quality policy.",
    },
    {
        "key": "workflow_exchange_auto_update_public",
        "label": "Auto Update Public",
        "type": "bool",
        "default": DEFAULT_SETTINGS["workflow_exchange_auto_update_public"],
        "help": "Automatically update public bundles that pass safety and quality policy.",
    },
    {
        "key": "workflow_exchange_exclude_share_skills",
        "label": "Exclude Share Skills",
        "type": "list",
        "default": DEFAULT_SETTINGS["workflow_exchange_exclude_share_skills"],
        "help": "Skill ids that should never be shared.",
    },
    {
        "key": "workflow_exchange_exclude_share_skill_categories",
        "label": "Exclude Share Skill Categories",
        "type": "list",
        "default": DEFAULT_SETTINGS["workflow_exchange_exclude_share_skill_categories"],
        "help": "Skill categories that should never be shared.",
    },
    {
        "key": "workflow_exchange_exclude_share_tags",
        "label": "Exclude Share Tags",
        "type": "list",
        "default": DEFAULT_SETTINGS["workflow_exchange_exclude_share_tags"],
        "help": "Workflow tags excluded from sharing.",
    },
    {
        "key": "workflow_exchange_exclude_share_titles",
        "label": "Exclude Share Titles",
        "type": "list",
        "default": DEFAULT_SETTINGS["workflow_exchange_exclude_share_titles"],
        "help": "Exact workflow titles excluded from sharing.",
    },
    {
        "key": "workflow_exchange_exclude_share_title_regex",
        "label": "Exclude Share Title Regex",
        "type": "list",
        "default": DEFAULT_SETTINGS["workflow_exchange_exclude_share_title_regex"],
        "help": "Regex patterns for workflow titles excluded from sharing.",
    },
    {
        "key": "workflow_exchange_exclude_update_skills",
        "label": "Exclude Update Skills",
        "type": "list",
        "default": DEFAULT_SETTINGS["workflow_exchange_exclude_update_skills"],
        "help": "Skill ids excluded from update candidates.",
    },
    {
        "key": "workflow_exchange_exclude_update_skill_categories",
        "label": "Exclude Update Skill Categories",
        "type": "list",
        "default": DEFAULT_SETTINGS["workflow_exchange_exclude_update_skill_categories"],
        "help": "Skill categories excluded from update candidates.",
    },
    {
        "key": "workflow_exchange_exclude_update_tags",
        "label": "Exclude Update Tags",
        "type": "list",
        "default": DEFAULT_SETTINGS["workflow_exchange_exclude_update_tags"],
        "help": "Workflow tags excluded from update candidates.",
    },
    {
        "key": "workflow_exchange_exclude_update_titles",
        "label": "Exclude Update Titles",
        "type": "list",
        "default": DEFAULT_SETTINGS["workflow_exchange_exclude_update_titles"],
        "help": "Exact workflow titles excluded from update candidates.",
    },
    {
        "key": "workflow_exchange_exclude_update_title_regex",
        "label": "Exclude Update Title Regex",
        "type": "list",
        "default": DEFAULT_SETTINGS["workflow_exchange_exclude_update_title_regex"],
        "help": "Regex patterns for workflow titles excluded from update candidates.",
    },
    {
        "key": "workflow_exchange_exclude_install_publishers",
        "label": "Exclude Install Publishers",
        "type": "list",
        "default": DEFAULT_SETTINGS["workflow_exchange_exclude_install_publishers"],
        "help": "Anonymous publisher ids excluded from install.",
    },
    {
        "key": "workflow_exchange_exclude_install_federations",
        "label": "Exclude Install Federations",
        "type": "list",
        "default": DEFAULT_SETTINGS["workflow_exchange_exclude_install_federations"],
        "help": "Federation ids excluded from install.",
    },
    {
        "key": "workflow_exchange_publish_top_k",
        "label": "Publish Top K",
        "type": "number",
        "default": DEFAULT_SETTINGS["workflow_exchange_publish_top_k"],
        "help": "Maximum number of top local workflows to consider for exchange publishing.",
    },
]
